version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "events-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jtycvkoeaqw6"
s3_prefix = "events-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
